#! /usr/bin/env python3
#-*- coding: UTF-8 -*-

### Legal
#
# Author:  Thomas DEBESSE <dev@illwieckz.net>
# License: ISC
# 

import Urcheon.Urcheon

if __name__ == "__main__":
	Urcheon.Urcheon.main()
