#! /bin/sh

# generate a README.md file with up-to-date built-in help.

test -f "README.md" && rm "README.md"
exec 1<&-
exec 1<>"README.md"

cat <<\EOF
Urcheon
=======

Urcheon is the Middle English term for “hedgehog”, used to refer the related ordinary in heraldry.

![Cute Granger](doc/cute-granger.512.png)  
_My lovely granger needs a tender knight to care for his little flower._

Description
-----------

This is a toolset to modify `.map` and `.bsp` files and to package `.pk3` files.

This toolset is currently [Unvanquished](http://unvanquished.net)-centric, but could be extended in the future.

This toolset was initially developed for the [Interstellar Oasis](https://github.com/interstellar-oasis/interstellar-oasis) initiative.

Help
----

```
$ urcheon bsp -h
EOF

./urcheon bsp -h

cat <<\EOF
```

Currently, `urcheon map` does not parse vertex matrices yet, it carbon copies them instead.

```
$ urcheon map -h
EOF

./urcheon map -h

cat <<\EOF
```

The `urcheon pak` stage relies on [`q3map2` from netradiant](https://gitlab.com/xonotic/netradiant), the one maintained by the Xonotic team. The navmesh code merge is still pending so you must use my [navmesh branch](https://gitlab.com/illwieckz/netradiant/commits/navmesh) if you use `urcheon pak` to build map packages. Other `urcheon pak` dependencies are: [`convert` from ImageMagick](https://www.imagemagick.org/), [`cwebp` from Google](https://developers.google.com/speed/webp/docs/cwebp), [`crunch` from Unvanquished](https://github.com/Unvanquished/crunch), [`opusenc` from Xiph](http://opus-codec.org), and if you need to convert iqe models, [`iqm` from Sauerbraten](http://sauerbraten.org/iqm/).


```
$ urcheon pak -h
EOF

./urcheon pak -h

cat <<\EOF
```

Warning
-------

No warranty is given, use this at your own risk.

Author
------

Thomas Debesse <dev@illwieckz.net>

Copyright
---------

This script is distributed under the highly permissive and laconic [ISC License](COPYING.md).
EOF

#EOF
